title: Mubarak Mohamed - Cybersecurity Analyst
description: Portfolio website of Mubarak Mohamed, Cybersecurity Analyst
baseurl: /portfolio
url: https://mubarakmohamed99.github.io
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
